---
execute:               # Default settings for code blocks
  warning: false       # Do not print warnings
  message: false       # Do not print messages
  size: "scriptsize"   # Set code size to script size

format:
  pdf:        # Specify .pdf formatting options 
    documentclass: article     # Document Class
    number-sections: true      # Number Sections
    reference-section-title: "References" # Title for reference section
    code-line-numbers: true    # Line numbers printed in code
    cap-location: top          # Captions at the top of tables 
    geometry:
      - top=0.75in
      - left=0.75in
      - bottom=0.75in
      - right=0.75in
format-links: [pdf]
---
```{r}
#| echo: false

default_chunk_hook  <- knitr::knit_hooks$get("chunk")

latex_font_size <- c("Huge", "huge", "LARGE", "Large", 
                     "large", "normalsize", "small", 
                     "footnotesize", "scriptsize", "tiny")

knitr::knit_hooks$set(chunk = function(x, options) {
  x <- default_chunk_hook(x, options)
  if(options$size %in% latex_font_size) {
    paste0("\n \\", options$size, "\n\n", 
      x, 
      "\n\n \\normalsize"
    )
  } else {
    x
  }
})

```

```{r}
#| label: load-packages
#| include: false
library(tidyverse)
library(rvest)
```

<!-- Code For Building Menu Here -->
```{r}
#| include: false
breakfasts <- c("website/BerryMelonSmoothie.html",
                "website/BiscuitsAndGravy.html",
                "website/BreakfastCheesecake.html",
                "website/BreakfastMuffins.html",
                "website/ChiaParfait.html",
                "website/GardenTomatoQuiche.html",
                "website/OvernightOats.html",
                "website/PumpkinToast.html",
                "website/TropicalSmoothie.html")
dinner <- c("website/AfricanPeanutSoup.html",
            "website/Alfredo.html",
            "website/ArugulaPasta.html",
            "website/AutumnGrainBowl.html",
            "website/BakedZiti.html",
            "website/BBQChili.html",
            "website/Bibimbap.html",
            "website/BLTSalad.html",
            "website/Burgers.html",
            "website/CapreseSandwiches.html",
            "website/EggplantParmesan.html",
            "website/Enchiladas.html",
            "website/FloridaRolls.html",
            "website/KimchiGrilledCheese.html",
            "website/Lasagna.html",
            "website/LatinBowl.html",
            "website/Meatloaf.html",
            "website/PadThai.html",
            "website/PastaAndPeas.html",
            "website/Pizza.html",
            "website/RedWineRagu.html",
            "website/SalmonChowder.html",
            "website/Shakshuka.html")
```

```{r}
dinner.choices = sample(dinner, 3, replace=FALSE) #grabs 3 random dinners, not replace, becasue I don't want multiple of the same recipe
bfast.choice = sample(breakfasts, 1, replace = FALSE) #one random bfast

meals = c(dinner.choices,bfast.choice)
(meals)

```

```{r}
scrape.html = function(meal){ #takes in the link of the meal

  #copying what i did in lab4:
  recipe.item = read_html(meal)
  recipe.title <- html_text(html_element(recipe.item, "h1")) #put this in after to save me headaches when i just want to grab this info from the function

  ingredients.section = html_element(recipe.item, "#ingredients")
  ingredients = html_elements(ingredients.section, "li")

  instructions.section = html_element(recipe.item, "#instructions")
  instructions = html_elements(instructions.section, "li")

  image.element = html_element(recipe.item, ".figure-img")
  image.url = paste("website/",html_attr(image.element, "src"), sep="")
  
  return(list(title = recipe.title, img.url = image.url, ingredients = ingredients, instructions = instructions))
}
recipes = lapply(meals,scrape.html)
(recipes)
```

```{r}
for(i in length(meals)){
  scrape.html(meals[i])

}

```


# Ingredients

\newpage

# Recipe One

\newpage

# Recipe Two

\newpage

# Recipe Three

\newpage

# Breakfast Recipe
